export const MAX_EVENT_COUNT = 2000;
export const MAX_TEXT_LENGTH = 2000;
export const MAX_URL_LENGTH = 4096;
export const MAX_NETWORK_BODY_LENGTH = 4000;

export const PAGE_BRIDGE_SOURCE = "BROWSER_RECORDER_DEBUGGER_PAGE_BRIDGE";
export const BACKGROUND_LISTENER_FLAG = "__browserRecorderDebuggerBackgroundListenerRegistered";

export const DEBUGGER_SESSIONS_STORAGE_KEY = "browserRecorderDebuggerSessions";
export const DEBUGGER_REPLAY_BUFFERS_STORAGE_KEY = "browserRecorderDebuggerReplayBuffers";
export const DEBUGGER_SESSION_ID_STORAGE_KEY = "debuggerSessionId";

export const START_SESSION_MESSAGE = "BROWSER_RECORDER_DEBUGGER_START_SESSION";
export const MARK_RECORDING_STARTED_MESSAGE = "BROWSER_RECORDER_DEBUGGER_MARK_RECORDING_STARTED";
export const GET_SESSION_SNAPSHOT_MESSAGE = "BROWSER_RECORDER_DEBUGGER_GET_SESSION_SNAPSHOT";
export const DISCARD_SESSION_MESSAGE = "BROWSER_RECORDER_DEBUGGER_DISCARD_SESSION";
export const PAGE_EVENT_MESSAGE = "BROWSER_RECORDER_DEBUGGER_PAGE_EVENT";
export const PAGE_EVENTS_MESSAGE = "BROWSER_RECORDER_DEBUGGER_PAGE_EVENTS";
export const ENSURE_PAGE_RUNTIME_MESSAGE = "BROWSER_RECORDER_DEBUGGER_ENSURE_PAGE_RUNTIME";
